package randoop.output;

import java.io.IOException;

/**
 * An exception (usually an IOException) occurred while writing tests to a file.
 */
@org.checkerframework.framework.qual.AnnotatedFor("org.checkerframework.checker.mustcall.MustCallChecker")
public class RandoopOutputException extends Throwable {

    private static final  @org.checkerframework.checker.mustcall.qual.MustCall({}) long serialVersionUID = -9104568425559719500L;

    /**
     * Creates a {@link RandoopOutputException} with the message.
     *
     * @param message the error message
     */
    @org.checkerframework.dataflow.qual.SideEffectFree
    public RandoopOutputException(@org.checkerframework.checker.mustcall.qual.MustCall({}) String message) {
        super(message);
    }

    /**
     * Creates a {@link RandoopOutputException} with the message and cause.
     *
     * @param message the error message
     * @param cause the exception for the error
     */
    @org.checkerframework.dataflow.qual.SideEffectFree
    public RandoopOutputException(@org.checkerframework.checker.mustcall.qual.MustCall({}) String message, @org.checkerframework.checker.mustcall.qual.MustCall({}) IOException cause) {
        super(message, cause);
    }

    /**
     * Creates a {@link RandoopOutputException} with the cause.
     *
     * @param cause the exception for the error
     */
    @org.checkerframework.dataflow.qual.SideEffectFree
    public RandoopOutputException(@org.checkerframework.checker.mustcall.qual.MustCall({}) IOException cause) {
        super(cause);
    }
}
